### ISSUE TITLE
Application aborts whith error "MPEG Audio head not found"

### ISSUE THREAD

**Issue by till-f** [till-f/MP3-Optimizer-for-Blue-Me#3]
Application aborts whith error "MPEG Audio header not found":

![image](https://user-images.githubusercontent.com/60755135/156849283-8062a55a-26af-4d4a-8e7b-e4ba59a597ec.png)
 
_Originally posted by @BunnyRaizo in https://github.com/till-f/MP3-Optimizer-for-Blue-Me/issues/1#issuecomment-1059570586_

**Comment by BunnyRaizo** [comment]
I literally did nothing,I opened the app,selected the folder with the music and this pops up.
And it's not just one problematic file,it's my whole music library with 668 songs

**Comment by till-f** [comment]
I suspect that you have a corrupted mp3 file somewhere (e.g. a filed named ".mp3" which is not really an mp3 but another audio file like wma). Version 1.1.2.0 should work better for you. It will not abort in such a case but skip and log the problematic files. Please do the same with the new version and attach the log file here that was created.

**Comment by BunnyRaizo** [comment]
[2022-03-08_180000.log](https://github.com/till-f/MP3-Optimizer-for-Blue-Me/files/8207723/2022-03-08_180000.log)
So basically my songs are corrupted?
But it shows only 7 songs out of 668 ones that don't work..
Except from that,those songs do work on my car,only newly downloaded songs don't work

Edit: Apparently the other songs did get their titles changed etc.
I'll test them on the car soon and let you know if it worked.
Thank you for all your help again <3

**Comment by till-f** [comment]
Well, something is odd with those 7 songs for sure. The error is thrown by the TagLib library. It is not developed by me and it might be that it also has some issues, but I doubt that they would miss such an obvious problem (TagLib is widely used).

Because only 7 songs are affected you might be able to fix them manually with [Mp3Tag](https://www.mp3tag.de/en/index.html) or similar tools. Mp3Tag might also give some more information what is wrong with these files.

I'll close this issue because I cannot do anything against it.
